unit TestuCalculadora;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, Math, uCalculadora;

type
  // Test methods for class TCalculadora

  TestTCalculadora = class(TTestCase)
  strict private
    FCalculadora: TCalculadora;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCalculaLitros;
    procedure TestCalculaValor;
    procedure TestCalculaImposto;
  end;

implementation

procedure TestTCalculadora.SetUp;
begin
  FCalculadora := TCalculadora.Create;
end;

procedure TestTCalculadora.TearDown;
begin
  FCalculadora.Free;
  FCalculadora := nil;
end;

procedure TestTCalculadora.TestCalculaLitros;
var
  ReturnValue: Double;
  Preco: Double;
  Valor: Double;
begin
  Preco := 5;
  Valor := 20;
  ReturnValue := FCalculadora.CalculaLitros(Valor, Preco);
  CheckEquals(4, ReturnValue);
end;

procedure TestTCalculadora.TestCalculaValor;
var
  ReturnValue: Double;
  Preco: Double;
  Litros: Double;
begin
  Preco := 5;
  Litros := 20;
  ReturnValue := FCalculadora.CalculaValor(Litros, Preco);
  CheckEquals(100, ReturnValue);
end;

procedure TestTCalculadora.TestCalculaImposto;
var
  ReturnValue: Double;
  taxa: Double;
  Valor: Double;
begin
  taxa := 13;
  Valor := 100;
  ReturnValue := FCalculadora.CalculaImposto(Valor, taxa);
  CheckEquals(13, ReturnValue);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCalculadora.Suite);
end.

